[package]
name = "d02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
strum = { version = "0.25.0", features = ["derive"] }
test-case = "3.3.1"
